### ISSUE TITLE
Setting up traffic log for surmise

### ISSUE THREAD

**Issue by mosesyhc** [surmising/surmise#43]

**Comment by mosesyhc** [comment]
@wildsm: following up on previous conversation about logging traffic for surmise.  Can you give a pointer as to where to begin? I will implement.

**Comment by wildsm** [comment]
Following the approach given at https://github.com/bandframework/bandframework/issues/18

This has now been implemented in the private repo (surmise team all added)
https://github.com/surmising/surmisedatacollection

I have successfully tested a manual run.

I suggest @mosesyhc wait 24 hours and confirm at the above repo (in the `github-repo-stats ` branch) that new data was grabbed (since it runs once per day) and check that the pdf report linked in the README is good.
After that, this issue can be closed.

Thanks for raising it!

**Comment by mosesyhc** [comment]
Verified that report is successfully generated in branch. Closing issue.
